services:
    _defaults:
        autoconfigure: true

    contao_comments.cron.purge_subscriptions:
        class: Contao\CommentsBundle\Cron\PurgeSubscriptionsCron
        arguments:
            - '@contao.framework'
            - '@?monolog.logger.contao.cron'
