services:
    _defaults:
        autoconfigure: true

    contao_comments.cron.purge_subscriptions:
        class: Contao\CommentsBundle\Cron\PurgeSubscriptionsCron
        arguments:
            - '@contao.framework'
            - '@?monolog.logger.contao.cron'

    contao_comments.listener.data_container.add_comment_fields:
        class: Contao\CommentsBundle\EventListener\DataContainer\AddCommentFieldsListener
        arguments:
            - '%kernel.bundles%'
